version: "3.8"
services:
  app:
    container_name: app
    image: node
    restart: always
    build:
      dockerfile: Dockerfile
    volumes:
      - './:/appadonis'
      - '/appadonis/node_modules'
    ports:
      - "3333:3333"
    environment:
      - CHOKIDAR_USEPOLLING=true
    links:
      - db-mysql

  db-mysql:
    image: mysql:5.6
    platform: linux/x86_64
    container_name: db-mysql
    restart: on-failure
    env_file: .env
    environment:
        MYSQL_DATABASE: ${MYSQL_DB_NAME}
        MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_USER: ${MYSQL_USER}
        SERVICE_TAGS: dev
        SERVICE_NAME: mysql
    volumes:
        - ./database-mysql:/docker-entrypoint-initdb.d
        - ./database-mysql:/var/lib/mysql:rw
    ports:
        - 33069:3306